<ul>
<?php foreach ($this->getItems() as $_item) : ?>
    <?php
    // Mage_Sales_Model_Order_Item;
    $_item = Mage::getModel('catalog/product')->load($_item->getProductId());
    ?>
    <li><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $_item['name'] ?> </a>
    </li>
    <li><img
        src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(75, 75) ?>"
        width="75" height="75"
        alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></li>
    <li><?php echo $_item->getFinalPrice() ?></li>

<?php endforeach; ?>

</ul>